# Generated by Django 5.1.3 on 2025-05-04 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Kategori Adı")),
            ],
            options={
                "verbose_name": "Kategori",
                "verbose_name_plural": "Kategoriler",
            },
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Kitap Adı")),
                ("author", models.CharField(max_length=100, verbose_name="Yazar")),
                ("description", models.TextField(verbose_name="Açıklama")),
                ("page_count", models.IntegerField(verbose_name="Sayfa Sayısı")),
                ("language", models.CharField(max_length=50, verbose_name="Dil")),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=1, max_digits=3, verbose_name="Puan"
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(upload_to="covers/", verbose_name="Kapak Resmi"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Eklenme Tarihi"
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        to="books.category", verbose_name="Kategoriler"
                    ),
                ),
            ],
            options={
                "verbose_name": "Kitap",
                "verbose_name_plural": "Kitaplar",
            },
        ),
        migrations.CreateModel(
            name="UserLibrary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "added_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Eklenme Tarihi"
                    ),
                ),
                (
                    "completion",
                    models.IntegerField(default=0, verbose_name="Tamamlanma Yüzdesi"),
                ),
                (
                    "last_read",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Son Okunma Tarihi"
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="books.book",
                        verbose_name="Kitap",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kullanıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kullanıcı Kütüphanesi",
                "verbose_name_plural": "Kullanıcı Kütüphaneleri",
                "unique_together": {("user", "book")},
            },
        ),
    ]
