# Generated by Django 5.1.3 on 2025-05-04 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="google_books_id",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Google Books ID"
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="published_date",
            field=models.DateField(blank=True, null=True, verbose_name="Yayın Tarihi"),
        ),
        migrations.AddField(
            model_name="book",
            name="publisher",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Yayınevi"
            ),
        ),
    ]
