# Generated by Django 5.1.3 on 2025-05-04 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_book_google_books_id_book_published_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="cover_image_url",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="Kapak Resmi URL"
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="cover_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="covers/", verbose_name="Kapak Resmi"
            ),
        ),
    ]
