# Generated by Django 5.2.1 on 2025-05-16 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userbook",
            name="finish_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userbook",
            name="reading_goal_daily",
            field=models.IntegerField(default=0, help_text="Günlük sayfa hedefi"),
        ),
        migrations.AddField(
            model_name="userbook",
            name="reading_status",
            field=models.CharField(
                choices=[
                    ("want_to_read", "Okuyacağım"),
                    ("reading", "Okuyorum"),
                    ("read", "Okudum"),
                ],
                default="want_to_read",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userbook",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userbook",
            name="total_reading_time",
            field=models.IntegerField(
                default=0, help_text="Toplam okuma süresi (dakika)"
            ),
        ),
        migrations.CreateModel(
            name="ReadingGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target_books", models.IntegerField(default=0)),
                ("target_pages", models.IntegerField(default=0)),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("daily", "Günlük"),
                            ("weekly", "Haftalık"),
                            ("monthly", "Aylık"),
                            ("yearly", "Yıllık"),
                        ],
                        max_length=10,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_completed", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reading_goals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReadingSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("duration", models.IntegerField(help_text="Okuma süresi (dakika)")),
                ("pages_read", models.IntegerField(default=0)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "user_book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reading_sessions",
                        to="books.userbook",
                    ),
                ),
            ],
        ),
    ]
