# Generated by Django 5.0.14 on 2025-05-17 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_userbook_finish_date_userbook_reading_goal_daily_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="language",
        ),
        migrations.AddField(
            model_name="book",
            name="publication_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
